info:
  name: "Zuul Edge Server"
  description: "Gateway to Drucare"

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

spring:
  application:
    name: Zuul-EdgeServer
  cloud:
    config:
      uri: http://192.168.1.101:8888
##      uri: ${vcap.services.${PREFIX:}configserver.credentials.uri:http://user:password@localhost:8888}

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
#  ignoredServices: "*"
#  routes:
#    servicea:
#      path: /servicea/**
#      serviceId: servicea

  
server:
  port: 8765

#logging:
#  level:
#    ROOT: INFO
#    org.springframework.web: INFO

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.1.101:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
#    metadataMap:
#      hostname: ${vcap.application.application_uris[0]}
#      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}

#security:
#  oauth2:    
#    client:
#      accessTokenUri: http://localhost:9999/uaa/oauth/token
#      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
#      clientId: eagleeye
#      clientSecret: thisissecret   
#    resource:
#      userInfoUri: http://localhost:9999/uaa/user
#      preferTokenInfo: true  
#  sessions: ALWAYS

management:
  security:
    enabled: false
  
